name: frhooks
description: Use react hooks in flutter!
version: 1.5.2
homepage: https://github.com/huangbinjie/frhooks

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
