name: frhooks
description: use react like hooks in flutter!
version: 1.4.3
homepage: https://github.com/huangbinjie/frhooks

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
